# Generated by Django 2.1.8 on 2019-04-18 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
                ('religion', models.TextField(blank=True)),
                ('hobby', models.TextField(blank=True)),
                ('like_food', models.TextField(blank=True)),
            ],
        ),
    ]
