# Generated by Django 2.1.8 on 2019-04-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduce',
            old_name='like_food',
            new_name='like_it',
        ),
        migrations.AlterField(
            model_name='introduce',
            name='hobby',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='introduce',
            name='religion',
            field=models.TextField(max_length=50),
        ),
    ]
